export let products = [
  // Zapatos
  {
    id: 1,
    title: "Zapato deportivo",
    description: "Cómodos para correr",
    price: 59.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714055863/productos/Zapatos/ueaanhlsktzl7oouim36.jpg",
    category: "Zapatos",
  },
  {
    id: 2,
    title: "Zapato casual",
    description: "Estilo y confort para el día a día",
    price: 49.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714055863/productos/Zapatos/lj4clna6h0osdwbnywiz.jpg",
    category: "Zapatos",
  },
  {
    id: 3,
    title: "Botas de trabajo",
    description: "Resistentes para cualquier obra",
    price: 89.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714055863/productos/Zapatos/qsiuthgtbiic1rvfaaoa.jpg",
    category: "Zapatos",
  },
  {
    id: 4,
    title: "Sandalias",
    description: "Ideales para el verano",
    price: 29.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714055863/productos/Zapatos/qkfmsbanogz1wbf2r0by.jpg",
    category: "Zapatos",
  },
  {
    id: 5,
    title: "Mocasines",
    description: "Elegancia clásica",
    price: 79.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714055863/productos/Zapatos/mvevcgaguf7xzgpxvilo.jpg",
    category: "Zapatos",
  },

  // Camisas
  {
    id: 6,
    title: "Camisa de vestir",
    description: "Perfecta para eventos formales",
    price: 39.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063370/productos/camisas/q74919gujnpnmr1meglt.jpg",
    category: "Camisas",
  },
  {
    id: 7,
    title: "Camisa polo",
    description: "Casual pero arreglado",
    price: 34.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063370/productos/camisas/bbivr6gjfpt773al2xh3.jpg",
    category: "Camisas",
  },
  {
    id: 8,
    title: "Camisa manga larga",
    description: "Versátil para todas las estaciones",
    price: 29.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063370/productos/camisas/vebfadgbp4xn7wbcztrs.jpg",
    category: "Camisas",
  },
  {
    id: 9,
    title: "Franela",
    description: "Calidez y comodidad",
    price: 24.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063370/productos/camisas/enjtha6mfyy062wb34tp.jpg",
    category: "Camisas",
  },
  {
    id: 10,
    title: "Camiseta básica",
    description: "Un básico indispensable",
    price: 14.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063370/productos/camisas/ce8uwdsk4lcnka5tfews.jpg",
    category: "Camisas",
  },

  // Pantalones
  {
    id: 11,
    title: "Jean",
    description: "Resistentes y siempre de moda",
    price: 49.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063721/productos/Pantalones/Men_s_Double_L_Jeans_Natural_Fit_Hidden_Comfort_Cotton_knwekr.jpg",
    category: "Pantalones",
  },
  {
    id: 12,
    title: "Pantalon chinos",
    description: "Elegancia casual",
    price: 44.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063719/productos/Pantalones/Washed_Dark_Gray_Stretch_Chino_Pants_lkgwqr.jpg",
    category: "Pantalones",
  },
  {
    id: 13,
    title: "Pantalon de vestir",
    description: "Formalidad y estilo",
    price: 59.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063718/productos/Pantalones/Beige_caqui_yw1tc2.jpg",
    category: "Pantalones",
  },
  {
    id: 14,
    title: "Pantalon cargo",
    description: "Comodidad y capacidad",
    price: 39.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063716/productos/Pantalones/Ropa_de_calle_pantalones_negros_para_mujer_pantalones_el%C3%A1sticos_de_cintura_de_estilo_coreano_pantalones_holgados_pantalones_Harajuku_de_Hip_Hop_para_verano_y_oto%C3%B1o_para_mujer_-_K15_Black___Chinese_Size_M___CHIN_xnzhwa.jpg",
    category: "Pantalones",
  },
  {
    id: 15,
    title: "Short",
    description: "Frescura para los días calurosos",
    price: 19.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063715/productos/Pantalones/Boys_Nike_Black_Essential_Shorts_-_Black_yc3q7n.jpg",
    category: "Pantalones",
  },

  // Abrigos
  {
    id: 16,
    title: "Abrigo de lana",
    description: "Elegante y abrigado",
    price: 129.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063903/productos/Abrigos/Men_Letter_Patched_Zip_Up_Corduroy_Thermal_Coat_ebboh8.jpg",
    category: "Abrigos",
  },
  {
    id: 17,
    title: "Chaqueta impermeable",
    description: "Protección contra la lluvia",
    price: 79.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063895/productos/Abrigos/Utility_Jacket_Windproof_And_Waterproof_Men_s_Sports_Jacket_Outdoor_Windbreaker_Gym_Clothes_Men_wtwevy.jpg",
    category: "Abrigos",
  },
  {
    id: 18,
    title: "Parka con capucha",
    description: "Estilo urbano y funcional",
    price: 109.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063900/productos/Abrigos/EMMETT_-_Parka_with_removable_hat_-_Dunkelblau___S_hcfscc.jpg",
    category: "Abrigos",
  },
  {
    id: 19,
    title: "Chaleco acolchado",
    description: "Calidez sin mangas",
    price: 49.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063897/productos/Abrigos/Thick_Warm_Sleeveless_Coat_Stand_Collar_Inluslated_Padded_Vest_for_Men_plus_Size_M-4XL_-_Army_Green___XL_whalbq.jpg",
    category: "Abrigos",
  },
  {
    id: 20,
    title: "Abrigo de Algodon",
    description: "Muy Calido",
    price: 29.99,
    img: "https://res.cloudinary.com/dl7jojha3/image/upload/v1714063904/productos/Abrigos/Men_s_Winter_Coat_Winter_Jacket_Fleece_Jacket_Work_Jacket_Daily_Wear_Vacation_Warm_Pocket_Button-Down_Winter_Solid___Plain_Color_Comfort_Leisure_Turndown_Dark-Gray_Black_Dark_Blue_Military_Green_oq0mbj.jpg",
    category: "Abrigos",
  },
];
